name: End to end tests

on:
  pull_request:
    branches: "main"

jobs:
  test_guest:
    name: Test Guest Application
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Execute Tests
        working-directory: apps/guest
        run: npx playwright test
        env:
          SUPABASE_URL: ${{secrets.SUPABASE_URL}}
          SUPABASE_KEY: ${{secrets.SUPABASE_KEY}}
          NEXTAUTH_URL: ${{secrets.NEXTAUTH_URL}}
          NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      - name: Upload articats
        uses: actions/upload-artifact@v4
        with:
          path: apps/guest/playwright-report
          name: playwright-report-guest
          retention-days: 1
  test_hotel:
    name: Test Hotel Application
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Install nodejs
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install
      - name: Install browsers
        run: npx playwright install --with-deps
      - name: Execute Tests
        continue-on-error: true
        working-directory: apps/hotel
        run: npx playwright test
      - name: Upload artifcats
        uses: actions/upload-artifact@v4
        with:
          path: apps/hotel/playwright-report
          name: playwright-report-hotel
          retention-days: 1
